# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d178dd1275282896de777fd8891b03c3f406c4852515e640a3e5ba335764ac975d45b68ee9fde2d093504e004b1f26580eb32ae3fbcdecc0693d5383dcbbf3f

test:
  secret_key_base: c20a99a8867b93db29b6f2237a63990c7c7c3a64c17ac6d76a408778404be97430e6047d515fe8f73b11a2443f247ec11514c89e930c6ae3d76181d29114a579

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
